source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'AFNetworking', '~> 3.0'

target 'SignatureChecker_Tests', :exclusive => true do
  pod 'SignatureChecker', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
